### ISSUE TITLE
基于pod-template创建私有库

### ISSUE THREAD

**Issue by banzhuan-jing** [casatwy/PrivatePodGenerator#1]
大佬,考虑过修改https://github.com/CocoaPods/pod-template 然后创建私有库并创建Target和CTMediator分类文件么? 只修改 https://github.com/CocoaPods/pod-template/blob/master/setup/TemplateConfigurator.rb 文件就行.

**Comment by banzhuan-jing** [comment]
这样的话会简单很多

**Comment by banzhuan-jing** [comment]
使用的时候像这样: pod lib create MyLibrary --template-url=http://git.ycteam.work/pod-template.git (url是内网的)

**Comment by banzhuan-jing** [comment]
创建出来的目录结构像这样:

<img width="276" alt="屏幕快照 2019-04-25 下午4 54 23" src="https://user-images.githubusercontent.com/8119320/56723070-d5136580-677a-11e9-8281-3a697f35c17f.png">

**Comment by casatwy** [comment]
1. 这个方法很好，而且也不需要多少成本。但是我懒，每个业务团队自己做就行了。我们团队里能够做到跑一个bash命令就完成组件工程搭建和组件对应的category工程搭建。但这个bash命令是跟团队紧密相关的，所以不能开源。

2. 我看到你这边给到的工程结构跟我设计的工程结构不一样。我的设计初衷是：

A组件自己是一个Pod
B组件自己是一个Pod，target-action在B组件里
给CTMediator做的调用B组件功能的Category是一个Pod

3. A组件依赖Category Pod，并调用category pod中的方法完成对B组件的调用。A组件完全不依赖B组件。但主工程（也可以说是壳工程）依赖A和B组件，主工程不直接依赖category组件，是通过依赖A组件来间接依赖Category组件。

**Comment by banzhuan-jing** [comment]
是所有的category在一个pod么?

**Comment by banzhuan-jing** [comment]
还是一个category一个pod?

**Comment by casatwy** [comment]
针对一个组件的category放一个pod。
